### ISSUE TITLE
npm run build 之后运行报错 webpackJsonp is not defined

### ISSUE THREAD

**Issue by lq6667** [zhaoqize/vue-advance#1]
npm run build  打包之后，浏览器访问页面报错 Uncaught ReferenceError: webpackJsonp is not defined

**Comment by ansike** [comment]
![image](https://user-images.githubusercontent.com/25131706/31135072-94efe3a0-a829-11e7-8a97-58852c10a0ac.png)

需要在prod文件中把'manifest','vendor'都加进去
